### ISSUE TITLE
Postgre problems (fixed)

### ISSUE THREAD

**Issue by MartinKavik** [TuntematonSotilas/api_album#1]
Just some notes to postgre setup before I forget (maybe useful in readme):
- I've added `C:\Program Files\PostgreSQL\11\lib` into `Path` but I had to restart PC and especially run `cargo clean` to fix error:
```
...
= note: LINK : fatal error LNK1181: cannot open input file 'libpq.lib'
...
``` 
- I had to set `id` in `user` table as primary key - without it it's not possible to add records through `pgAdmin` (4).
- Import command: `psql -U postgres postgres < script.sql` (in `sql` folder). Note: I had to upgrade my Postgre from 9.x to 11.x).
- `script.sql` failes on lines like `ALTER TABLE public.picture OWNER TO bgael;` and there were some warnings/errors because of `fr_FR.UTF-8`. However import was successful.

---

You can close it.

**Comment by TuntematonSotilas** [comment]
- Restart PC and run cargo clean : added to README
- Primary key missing : added to the script
